### PR TITLE
finished the implementation of featurelization functions

### PR DESCRIPTION
**Pull request by LuxiWang99**
main.py scans through all the graphs in data/graph, and turns them into
edgelists in the "/graph". It calls node2vec to turn the graphs into vectors "/emb".
main.py returns a dict consists of node_one_hot and edge_one_hot and node distance (normalized)
in a pickle file called final_result.pickle.

### CODE REVIEW

**Comment by izgzhen** [comment]
Three general things:

- please don’t delete classifier.ipynb. https://stackoverflow.com/questions/37503999/restore-deleted-files-from-commit
- Move the new files under a new namespace. For example, ml-experiments. Since there are some top-level files only specific to this purpose.
- don’t commit generated intermediate files

**Comment by LuxiWang99** [comment]
fixed notes:
- classifier.ipynb is still there. I did not touch the code previously, although I think there might be some problem with the earlier feauturelization code. The newer version should have fixed all the issues. 
- put new files in ml-experiment
- deleted intermediate files

**Comment by izgzhen** [comment]
LGTM! However, it looks like there are some merge conflict. Also, after
fixing the merge conflict, please squash all the commits into one. (
https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/
)

Thanks again for your work!

-Zhen

**Comment by LuxiWang99** [comment]
I called 'git rebase -i [SHA]', [SHA] is my latest commit., and it returned: 'Successfully rebased and updated refs/heads/master.'. I am not sure if this is what you want me to do.

**Comment by izgzhen** [comment]
@LuxiWang99 The intended outcome is to "squash" (combine) all commits [here](https://github.com/uwplse/seguard-resources/pull/4/commits) into a single commit with a more meaningful commit message. This makes this repo's git history easier to understand.

Here is another tutorial on this topic: https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing

**Comment by izgzhen** [comment]
Another thing you could do to circumvent this is to move the new files you added to a temporary directory, and revert back to the `origin/master` of this repo. Then you copy the new files back from a temporary directory, add them and create a fresh new commit and push it to your fork.

**Comment by izgzhen** [comment]
I would suggest the second approach since there needs a bit more git ninja to resolve a rebase conflict in the first one.

**Comment by LuxiWang99** [comment]
I might have merged with some of your commits, but I think I squashed everything together.

**Comment by izgzhen** [comment]
@LuxiWang99 You are almost there :) Do the following on your own branch:

- update the origin code: `git fetch origin`
- rebase your changes w.r.t master: `git rebase origin/master`
- amend the commit message: `git commit --amend --reset-author`
    + make the commit message a single line describing what you did

**Comment by LuxiWang99** [comment]
Done

**Pull request merged**
